"""Layer-2 (IEEE 1588-2008 Annex H) constants for the E2E grandmaster."""

from __future__ import annotations

ETHERTYPE_PTP = 0x88F7
ETHERTYPE_VLAN = 0x8100
ETH_ADDR_LEN = 6

# G.8275.1 uses bridge-reserved addresses so transparent clocks can process the frames.
G82751_PTP_MAC = bytes.fromhex("0180C200000E")
# IEEE 1588-2008 default (flooded by ordinary bridges).
IEEE1588_PTP_MAC = bytes.fromhex("011B19000000")

HEADER_LEN = 34
ANNOUNCE_BODY_LEN = 30
SYNC_BODY_LEN = 10
FOLLOW_UP_BODY_LEN = 10
DELAY_REQ_BODY_LEN = 10
DELAY_RESP_BODY_LEN = 20

ANNOUNCE_MSG_LEN = HEADER_LEN + ANNOUNCE_BODY_LEN  # 64
SYNC_MSG_LEN = HEADER_LEN + SYNC_BODY_LEN  # 44
FOLLOW_UP_MSG_LEN = HEADER_LEN + FOLLOW_UP_BODY_LEN  # 44
DELAY_REQ_MSG_LEN = HEADER_LEN + DELAY_REQ_BODY_LEN  # 44
DELAY_RESP_MSG_LEN = HEADER_LEN + DELAY_RESP_BODY_LEN  # 54

CONTROL_SYNC = 0x00
CONTROL_FOLLOW_UP = 0x02
CONTROL_DELAY_RESP = 0x03
CONTROL_ANNOUNCE = 0x05

LOG_MSG_INTERVAL_NA = 0x7F

# flagField is 16-bit big-endian: octet 0 is the high byte (see ptp/constants.py
# FLAG_TWO_STEP / FLAG_UNICAST for octet-0 bits); Announce flags live in octet 1.
FLAG_LEAP61 = 1 << 0
FLAG_LEAP59 = 1 << 1
FLAG_UTC_OFFSET_VALID = 1 << 2
FLAG_PTP_TIMESCALE = 1 << 3
FLAG_TIME_TRACEABLE = 1 << 4
FLAG_FREQ_TRACEABLE = 1 << 5
FLAG_SYNC_UNCERTAIN = 1 << 6

ANNOUNCE_DEFAULT_FLAGS = FLAG_PTP_TIMESCALE | FLAG_TIME_TRACEABLE | FLAG_FREQ_TRACEABLE

TIME_SOURCE_GPS = 0x10
TIME_SOURCE_INTERNAL_OSCILLATOR = 0x48
